import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}><h4 className={styles.title}>Treekie</h4>
          <div className={styles.description}>Esportes ao ar livre</div>
        <nav className={styles.nav}>
          <ul className={styles.navlist}>
            <li className={styles['nav-bar-option']}>Sobre nós</li>
            <li className={styles['nav-bar-option']}>Dúvidas</li>
            <li className={styles['nav-bar-option']}>Suporte</li>
          </ul>
        </nav>

        <div className={styles['user-area']}>
            <button className={`${styles['user-button']} ${styles['user-button-sign']}`}>sign in</button>
            <button className={`${styles['user-button']} ${styles['user-button-log']}`}>log in</button>
        </div>
        </header>

        <div className={styles['groups-container']}>
          <div className={styles.card}>
            <img className={styles['card-png']} src="bike.png"></img>
            <label className={styles['card-label']}>Ciclismo</label>
          </div>
          <div className={styles.card}>
            <img className={styles['card-png']} src="escalada.png"></img>
            <label className={styles['card-label']}>Escalada</label>
          </div>
          <div className={styles.card}>
            <img className={styles['card-png']} src="box.png"></img>
            <label className={styles['card-label']}>Box</label>
          </div>
        </div>
      </main>

    </>
  )
}
