import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Card from 'components/grupo/card'
import FormCadastro from 'components/grupo/form_cadastro'
import ListCategorias from '../../components/categoria/data_list_categorias'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}><a href='http://localhost:3000' className={styles.title}>Trenkkie</a>
          <div className={styles.description}>Esportes ao ar livre</div>
          <nav className={styles.nav}>
            <ul className={styles.navlist}>
              <li className={styles['nav-bar-option']}>Sobre nós</li>
              <li className={styles['nav-bar-option']}>Dúvidas</li>
              <li className={styles['nav-bar-option']}>Suporte</li>
            </ul>
          </nav>

          <div className={styles['user-area']}>
            <button className={`${styles['user-button']} ${styles['user-button-sign']}`}>sign in</button>
            <button className={`${styles['user-button']} ${styles['user-button-log']}`}>log in</button>
          </div>
        </header>
        <div className="search-form-container">
          <form className={styles['form-search']}>
            <div className={styles['field']}>
              <label className={styles['form-label']}>Categoria</label>
              <input className={styles['form-input']} type="text" list="categorias" name="categoria"></input>
              <ListCategorias/>
            </div>
            <div className={styles['field']}>
              <label className={styles['form-label']}>min. participantes</label>
              <input className={styles['form-input']} type="number" name="minParticipantes" value={0}></input>
            </div>
            <div className={styles['field']}>
              <label className={styles['form-label']}>max. participantes</label>
              <input className={styles['form-input']} type="number" name="maxParticipantes"></input>
            </div>
            <div className={styles['field']}>
              <label className={styles['form-label']} htmlFor="nivel">Nível</label>
              <select className={styles['form-select-categorias']} name="nivel">
                <option value="iniciante">Iniciante</option>
                <option value="intermediario">Intermediario</option>
                <option value="avançado">Avançado</option>
              </select>
            </div>
            <div className={styles['button-container']}>
              <button className={styles['form-button']}> Buscar </button>
            </div>

          </form>
        </div>
        <Card/>
        <div className={styles['add-group']} onClick={()=> setShowModal(!showModal)}>+</div>
        {showModal ?<FormCadastro closeModal={ ()=> setShowModal(false)}/> : null}
      </main>

    </>
  )
}
